// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/twap/v1beta1/query.proto

package queryproto

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/osmosis-labs/osmosis/v11/x/twap/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetArithmeticTwapRequest struct {
	PoolId     uint64     `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	BaseAsset  string     `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset string     `protobuf:"bytes,3,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	StartTime  time.Time  `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	EndTime    *time.Time `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time,omitempty" yaml:"end_time"`
}

func (m *QueryGetArithmeticTwapRequest) Reset()         { *m = QueryGetArithmeticTwapRequest{} }
func (m *QueryGetArithmeticTwapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetArithmeticTwapRequest) ProtoMessage()    {}
func (*QueryGetArithmeticTwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_141a22dba58615af, []int{0}
}
func (m *QueryGetArithmeticTwapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetArithmeticTwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetArithmeticTwapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetArithmeticTwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetArithmeticTwapRequest.Merge(m, src)
}
func (m *QueryGetArithmeticTwapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetArithmeticTwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetArithmeticTwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetArithmeticTwapRequest proto.InternalMessageInfo

func (m *QueryGetArithmeticTwapRequest) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *QueryGetArithmeticTwapRequest) GetBaseAsset() string {
	if m != nil {
		return m.BaseAsset
	}
	return ""
}

func (m *QueryGetArithmeticTwapRequest) GetQuoteAsset() string {
	if m != nil {
		return m.QuoteAsset
	}
	return ""
}

func (m *QueryGetArithmeticTwapRequest) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *QueryGetArithmeticTwapRequest) GetEndTime() *time.Time {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type QueryGetArithmeticTwapResponse struct {
	ArithmeticTwap github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=arithmetic_twap,json=arithmeticTwap,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"arithmetic_twap" yaml:"arithmetic_twap"`
}

func (m *QueryGetArithmeticTwapResponse) Reset()         { *m = QueryGetArithmeticTwapResponse{} }
func (m *QueryGetArithmeticTwapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetArithmeticTwapResponse) ProtoMessage()    {}
func (*QueryGetArithmeticTwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_141a22dba58615af, []int{1}
}
func (m *QueryGetArithmeticTwapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetArithmeticTwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetArithmeticTwapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetArithmeticTwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetArithmeticTwapResponse.Merge(m, src)
}
func (m *QueryGetArithmeticTwapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetArithmeticTwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetArithmeticTwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetArithmeticTwapResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryGetArithmeticTwapRequest)(nil), "osmosis.gamm.twap.v1beta1.QueryGetArithmeticTwapRequest")
	proto.RegisterType((*QueryGetArithmeticTwapResponse)(nil), "osmosis.gamm.twap.v1beta1.QueryGetArithmeticTwapResponse")
}

func init() { proto.RegisterFile("osmosis/twap/v1beta1/query.proto", fileDescriptor_141a22dba58615af) }

var fileDescriptor_141a22dba58615af = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0xaf, 0xc7, 0xfe, 0x50, 0x4f, 0x62, 0x5a, 0x84, 0xa0, 0xeb, 0x68, 0x52, 0x05, 0x69, 0xaa,
	0x90, 0x66, 0xab, 0xe3, 0x02, 0x88, 0xcb, 0x2a, 0x24, 0xe0, 0x48, 0x34, 0x21, 0xc4, 0x25, 0x72,
	0x13, 0x93, 0x59, 0x24, 0x71, 0x1a, 0x3b, 0x1b, 0xbd, 0xf2, 0x09, 0x26, 0xed, 0x3b, 0x70, 0xe3,
	0xcc, 0x57, 0xe8, 0x71, 0x12, 0x17, 0xc4, 0x21, 0xa0, 0x96, 0x4f, 0xd0, 0x4f, 0x80, 0x6c, 0x27,
	0xdd, 0x18, 0x0c, 0x24, 0x4e, 0xc9, 0x7b, 0xbf, 0xdf, 0xfb, 0xf9, 0xe7, 0xe7, 0xf7, 0x60, 0x97,
	0x8b, 0x84, 0x0b, 0x26, 0xb0, 0x3c, 0x26, 0x19, 0x3e, 0xea, 0x0f, 0xa9, 0x24, 0x7d, 0x3c, 0x2a,
	0x68, 0x3e, 0x46, 0x59, 0xce, 0x25, 0xb7, 0xb6, 0x2a, 0x06, 0x8a, 0x48, 0x92, 0x20, 0x45, 0x43,
	0x15, 0xad, 0x7d, 0x33, 0xe2, 0x11, 0xd7, 0x2c, 0xac, 0xfe, 0x4c, 0x41, 0x7b, 0xe7, 0x8f, 0x92,
	0x2a, 0xf0, 0x73, 0x1a, 0xf0, 0x3c, 0xac, 0x78, 0x76, 0xa0, 0x89, 0x78, 0x48, 0x04, 0x5d, 0xd0,
	0x02, 0xce, 0xd2, 0x0a, 0xbf, 0x77, 0x11, 0xd7, 0x8e, 0x16, 0xac, 0x8c, 0x44, 0x2c, 0x25, 0x92,
	0xf1, 0x9a, 0x7b, 0x27, 0xe2, 0x3c, 0x8a, 0x29, 0x26, 0x19, 0xc3, 0x24, 0x4d, 0xb9, 0xd4, 0xa0,
	0xa8, 0xd0, 0xad, 0x0a, 0xd5, 0xd1, 0xb0, 0x78, 0x83, 0x49, 0x3a, 0xae, 0x21, 0x73, 0x88, 0x6f,
	0x6e, 0x61, 0x82, 0x0a, 0x72, 0x2e, 0x57, 0x49, 0x96, 0x50, 0x21, 0x49, 0x92, 0x19, 0x82, 0xfb,
	0x61, 0x09, 0x76, 0x5e, 0x28, 0x5f, 0x4f, 0xa9, 0xdc, 0xcf, 0x99, 0x3c, 0x4c, 0xa8, 0x64, 0xc1,
	0xc1, 0x31, 0xc9, 0x3c, 0x3a, 0x2a, 0xa8, 0x90, 0xd6, 0x6d, 0xb8, 0x96, 0x71, 0x1e, 0xfb, 0x2c,
	0x6c, 0x81, 0x2e, 0xe8, 0x2d, 0x7b, 0xab, 0x2a, 0x7c, 0x1e, 0x5a, 0x1d, 0x08, 0xd5, 0xb5, 0x7c,
	0x22, 0x04, 0x95, 0xad, 0xa5, 0x2e, 0xe8, 0x35, 0xbd, 0xa6, 0xca, 0xec, 0xab, 0x84, 0xe5, 0xc0,
	0xf5, 0x51, 0xc1, 0x65, 0x8d, 0x5f, 0xd3, 0x38, 0xd4, 0x29, 0x43, 0x78, 0x05, 0xa1, 0x90, 0x24,
	0x97, 0xbe, 0xf2, 0xd4, 0x5a, 0xee, 0x82, 0xde, 0xfa, 0x5e, 0x1b, 0x19, 0xc3, 0xa8, 0x36, 0x8c,
	0x0e, 0x6a, 0xc3, 0x83, 0xce, 0xa4, 0x74, 0x1a, 0xf3, 0xd2, 0xd9, 0x1c, 0x93, 0x24, 0x7e, 0xe4,
	0x9e, 0xd7, 0xba, 0x27, 0xdf, 0x1c, 0xe0, 0x35, 0x75, 0x42, 0xd1, 0x2d, 0x0f, 0x5e, 0xa7, 0x69,
	0x68, 0x74, 0x57, 0xfe, 0xa9, 0xbb, 0x3d, 0x29, 0x1d, 0x30, 0x2f, 0x9d, 0x0d, 0xa3, 0x5b, 0x57,
	0x1a, 0xd5, 0x35, 0x9a, 0x86, 0x8a, 0xea, 0x9e, 0x02, 0x68, 0x5f, 0xd5, 0x28, 0x91, 0xf1, 0x54,
	0x50, 0x6b, 0x04, 0x37, 0xc8, 0x02, 0xf1, 0xd5, 0xb0, 0xe8, 0x8e, 0x35, 0x07, 0xcf, 0x94, 0xf3,
	0xaf, 0xa5, 0xb3, 0x13, 0x31, 0x79, 0x58, 0x0c, 0x51, 0xc0, 0x93, 0xea, 0x99, 0xaa, 0xcf, 0xae,
	0x08, 0xdf, 0x62, 0x39, 0xce, 0xa8, 0x40, 0x4f, 0x68, 0x30, 0x2f, 0x9d, 0x5b, 0xc6, 0xcb, 0x25,
	0x39, 0xd7, 0xbb, 0x41, 0x7e, 0x39, 0x7a, 0xef, 0x13, 0x80, 0x2b, 0xda, 0x95, 0xf5, 0x11, 0xc0,
	0xcd, 0xdf, 0xac, 0x59, 0x0f, 0xd0, 0x95, 0x93, 0x8f, 0xfe, 0xfa, 0xec, 0xed, 0x87, 0xff, 0x51,
	0x69, 0xfa, 0xe0, 0xde, 0x7d, 0xff, 0xf9, 0xc7, 0xe9, 0x52, 0xc7, 0xda, 0xc6, 0xf5, 0x16, 0x29,
	0x89, 0xf3, 0xc1, 0xe7, 0x3c, 0x16, 0x83, 0x97, 0x93, 0xa9, 0x0d, 0xce, 0xa6, 0x36, 0xf8, 0x3e,
	0xb5, 0xc1, 0xc9, 0xcc, 0x6e, 0x9c, 0xcd, 0xec, 0xc6, 0x97, 0x99, 0xdd, 0x78, 0xfd, 0xf8, 0x42,
	0x97, 0x2a, 0x81, 0xdd, 0x98, 0x0c, 0xc5, 0x42, 0xed, 0xa8, 0xdf, 0xc7, 0xef, 0xcc, 0x66, 0x06,
	0x31, 0xa3, 0xa9, 0x34, 0x9b, 0x65, 0x9e, 0x76, 0x55, 0x7f, 0xee, 0xff, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xba, 0x03, 0x57, 0x5d, 0x15, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	GetArithmeticTwap(ctx context.Context, in *QueryGetArithmeticTwapRequest, opts ...grpc.CallOption) (*QueryGetArithmeticTwapResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetArithmeticTwap(ctx context.Context, in *QueryGetArithmeticTwapRequest, opts ...grpc.CallOption) (*QueryGetArithmeticTwapResponse, error) {
	out := new(QueryGetArithmeticTwapResponse)
	err := c.cc.Invoke(ctx, "/osmosis.gamm.twap.v1beta1.Query/GetArithmeticTwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	GetArithmeticTwap(context.Context, *QueryGetArithmeticTwapRequest) (*QueryGetArithmeticTwapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetArithmeticTwap(ctx context.Context, req *QueryGetArithmeticTwapRequest) (*QueryGetArithmeticTwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArithmeticTwap not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetArithmeticTwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetArithmeticTwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetArithmeticTwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.gamm.twap.v1beta1.Query/GetArithmeticTwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetArithmeticTwap(ctx, req.(*QueryGetArithmeticTwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.gamm.twap.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArithmeticTwap",
			Handler:    _Query_GetArithmeticTwap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/twap/v1beta1/query.proto",
}

func (m *QueryGetArithmeticTwapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetArithmeticTwapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetArithmeticTwapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndTime != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.EndTime):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintQuery(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x2a
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintQuery(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if len(m.QuoteAsset) > 0 {
		i -= len(m.QuoteAsset)
		copy(dAtA[i:], m.QuoteAsset)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QuoteAsset)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BaseAsset) > 0 {
		i -= len(m.BaseAsset)
		copy(dAtA[i:], m.BaseAsset)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BaseAsset)))
		i--
		dAtA[i] = 0x12
	}
	if m.PoolId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetArithmeticTwapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetArithmeticTwapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetArithmeticTwapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ArithmeticTwap.Size()
		i -= size
		if _, err := m.ArithmeticTwap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetArithmeticTwapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovQuery(uint64(m.PoolId))
	}
	l = len(m.BaseAsset)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.QuoteAsset)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovQuery(uint64(l))
	if m.EndTime != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.EndTime)
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetArithmeticTwapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ArithmeticTwap.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetArithmeticTwapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetArithmeticTwapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetArithmeticTwapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetArithmeticTwapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetArithmeticTwapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetArithmeticTwapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArithmeticTwap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ArithmeticTwap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
